# Generated by Django 2.0 on 2019-07-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_piezas_en_inventario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezas_en_inventario',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
