# Generated by Django 2.0 on 2019-07-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190712_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ventas',
            name='marca',
            field=models.CharField(default='000000', max_length=30),
        ),
        migrations.AddField(
            model_name='ventas',
            name='modelo',
            field=models.CharField(default='000000', max_length=30),
        ),
        migrations.AddField(
            model_name='ventas',
            name='numero_de_serie',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
